version: 2
updates:
  # Maintain dependencies for Python (uv)
  - package-ecosystem: "uv"
    directory: "/" # Location of pyproject.toml
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "bump"
      include: "scope"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflow files
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(ci)"
      include: "scope" 